In [4]:
#coding=utf-8

import tensorflow as tf
#下载input_data.py源代码,运行然后下载数据集
import input_data
import os 

os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

mnist = input_data.read_data_sets('MNIST_data/', one_hot=True)
#放置占位符
#这里的None表示此张量的第一个维度可以是任何长度的
x=tf.placeholder("float",[None,784])
#创建两个变量
#一个Variable代表一个可修改的张量
w=tf.Variable(tf.zeros([784,10]))
b=tf.Variable(tf.zeros([10]))

#使用TensorFlow自带的softmax回归线性模型
y=tf.nn.softmax(tf.matmul(x,w)+b)

#为了进行训练，需要把正确值一并传入网络
y_=tf.placeholder("float",[None,10])

#计算交叉墒
cross_entropy=-tf.reduce_sum(y_*tf.log(y))

#因为TensorFlow拥有一张描述你各个计算单元的图，它可以自动地使用反向传播算法(backpropagation algorithm)来
#有效地确定你的变量是如何影响你想要最小化的那个成本值的。然后，TensorFlow会用你选择的优化算法来不断地修改变量以降低成本。
#用梯度下降算法（gradient descent algorithm）以0.01的学习速率最小化交叉熵
train_step=tf.train.GradientDescentOptimizer(0.01).minimize(cross_entropy)

#初始化之前创建的变量的操作
#init=tf.initialize_all_variables()
init = tf.global_variables_initializer()

#在一个Session里面启动我们的模型，并且初始化变量
sess=tf.Session()
sess.run(init)

#开始训练模型，循环1000次，每次都会随机抓取训练数据中的100条数据，然后作为参数替换之前的占位符来进行train_step
for i in range(1000):
    batch_xs,batch_ys=mnist.train.next_batch(100)
    sess.run(train_step,feed_dict={x:batch_xs,y_:batch_ys})

#评估模型，tf.argmax能给出某个tensor对象在某一纬度上数据的最大索引，因为标签是由0,1组成，返回的索引就是数值为1的位置
correct_prediction=tf.equal(tf.argmax(y,1),tf.argmax(y_,1))

#计算正确预测项的比例，因为tf.equal返回的是布尔值,相等表示真，真的用ture,假的用false，
#使用tf.cast可以把布尔值转换成浮点数，tf.reduce_mean是求平均值
accuracy=tf.reduce_mean(tf.cast(correct_prediction,"float"))

print('打印模型参数w和b：')
print(accuracy)
print('===================')
print('测试集数据：')
print('images:')
print(mnist.test.images)
print(mnist.test.images.shape)
print('===================')
print('labels:')
print(mnist.test.labels)
print(mnist.test.labels.shape)
#在session中启动accuracy，输入是MNIST中的测试集
print(sess.run(accuracy,feed_dict={x:mnist.test.images,y_:mnist.test.labels}))


Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
打印模型参数w和b：
Tensor("Mean_3:0", shape=(), dtype=float32)
测试集数据：
images:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(10000, 784)
labels:
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(10000, 10)
0.9132
